[package]
name = "jsparse"
version = "0.1.0"
authors = ["Logan Smyth <loganfsmyth@gmail.com>"]

[dependencies]
ucd = "0.1.1"
# custom_derive = "0.1.7"
# enum_derive = "0.1.7"

# serde = "1.0.10"
# serde_json = "1.0"
